### ISSUE TITLE
I updated Flutter to version 3.27.1 and it gives me this error

### ISSUE THREAD

**Issue by AfshinNajafi74** [ARASHz4/flutter_jalali_date_picker#1]
'DialogThemeData' can't be assigned to a variable of type 'DialogTheme'.
 - 'DialogThemeData' is from 'package:flutter/src/material/dialog_theme.dart' ('/C:/flutter/packages/flutter/lib/src/material/dialog_theme.dart').
 - 'DialogTheme' is from 'package:flutter/src/material/dialog_theme.dart' ('/C:/flutter/packages/flutter/lib/src/material/dialog_theme.dart').
    final DialogTheme dialogTheme = Theme.of(context).dialogTheme;

**Comment by ARASHz4** [comment]
I fixed in new version
